---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

This is a collection of functions to make working with data from the [https://hcaidcs.phe.org.uk/](HCAI DCS) easier. 
The plan is to include Rmd documents to produce the IS six-monthly reports and other standard outputs, including the quarterly epidemiologic commentary. 

## Installation
Please email me for the zip file of the package. 
Once you have received the file, please do the following:
1.	Save the zip file to `H:\`     but do not unzip
1.	Open RStudio
1.	Run the following line: `install.packages(file.choose(), repos=NULL)`
1.	This will launch a file chooser where you can select the zip file you have just downloaded. This should install the package to the R package library. 

If installation is successful you will then be able to load the package with
`library(hcaidcs)`

## Use
Functions that begin `aec_` are intended for producing tables or plots for the annual epidemiologic commentary. 
Functions beginning `ann_tab_` are intended for the production of the annual tables. 

Functions prefixed `nice_` indicate that they format values for nice printing in text, such as financial year, or an estimate with its' 95% confidence interval. 
