---
title: "Producing the AEC"
author: "Simon Thelwall"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Producing the AEC}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction
The preparation of the Annual Epidemiological Commentary (AEC) is a complicated process. 
Most of the functions in this package have been written with the aim of simplifying the process. 
However, it remains complicated and this SOP/vignette sets out the process for it's preparation. 

The official statistics requirements mean that data for the AEC must be cross-checked by a second scientist within the Mandatory Surveillance team. 


## AEC Content
The AEC must contain the following: 

 * Executive summary
 * Introduction
 * [Description and links to annual tables](https://www.gov.uk/government/statistics/mrsa-mssa-and-e-coli-bacteraemia-and-c-difficile-infection-annual-epidemiological-commentary)
    * [Link to quarterly commentaries](http://www.hpa.org.uk/web/HPAweb&HPAwebStandard/HPAweb_C/1259151891722)
    * [Link to data quality statement](https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/514147/Mandatory_HCAI_surveillance_data_quality_statement.pdf)
  * A description of the following items
    * The commentary
    * Fingertips data
    * MyNHS 
  * Separate sections for each collection including the following subsections
    * Total reports
    * Trust-assigned/apportioned reports - as appropriate by collection. 
    * Age and sex distribution, including rate ratio comparisons in the text where appropriate
    * Time to onset
    * Source of bacteraemia
    * Geographic distribution of rates, by NHS local office (subregion) including [choropleth map](https://en.wikipedia.org/wiki/Choropleth_map) and table of rates by year. 
    * Dicussion
  * CDI should additionally have the following:
    * Trends in age and sex
    * the discussion section should mention interventions in detail. 
  * Appendices
    * Glossary
    * Methods: inclusion criteria, reporting to the DCS, deadline for data, CCG attribution, apportioning algorithm, PIR assignment, analysis of data, HCAI in Wales, Scotland and NI
    * References

Additional files include the following:

 * Annual data tables as .ODS format
 * Infographics, one per collection - liase with Jon White over production
 * Accompanying data in .ODS giving all the data used to create the tables and graphs in the report
 * Short summaries one for S. aureus, with separate sections for MRSA and MSSA, and one each for _E. coli_ and CDI
 

## Formatting 
Formatting should follow the PHE in-house style, with red hyperlinks.
The R markdown documents reference a pre-prepared template with most styling built in. The template can be found at [K:\\Annual_Publication_FY 15_16\\aectemplate.docx](K:\Annual_Publication_FY 15_16\aectemplate.docx)

## Preparation
### Project planning
The lead scientist should prepare a Gantt chart giving the expected time scales for the preparation of the report up to the date of publication. 
This should give the tasks per team member. 
An example can be found here: [K:\\Annual_Publication_FY 15_16\\misc](K:\Annual_Publication_FY 15_16\misc\Time line.xlsx)

The following should be described in the gantt chart:
 
 * Weekends
 * Annual leave per team member
 * Extraction date
 * Production of denominators
 * Production of commentary
 * Team checking
 * Amendments based on team feedback
 * Cross check of data
 * Production of formatting check list
 * Cross-check of data table formatting
 * Time for comment from DH
 * Time for amendments from DH
 * Date to go to web publishing
 * Date for pre release

The content of the Gannt chart should be agreed with other team members involved in the production of the AEC. 
 
### Folder structure

 * data - contains outputs and compiled extracts
 * denominators - contains raw and final denominator files
 * extracts - contains original data extracted from DCS
 * images - contains saved graphs or formulae
 * misc - contains timeline
 * scripts - contains any scripts for preparation of report, e.g. denominator preparation or cleaning scripts
 * table formatting - contains xlsx/ods files of supplementary data to be formatted for publication
 * web upload - contains final formatted files for upload to .gov.uk

### Denominator data preparation

### Data extraction
Data should be extracted around 20th April each year. 
Line lists can be extracted by information officers. 
*E. coli* data should be extracted to one file per year due to size and consequently time taken to download. 

## Report preparation
### Requirements
 
 * R & RStudio
 * [hcaidcs](http://bioinformatics-git.phe.gov.uk/Simon.Thelwall/hcaidcs) package. This is a user-written package available on gitlab.
 * 

#### Installation of hcaidcs
 1. Open RStudio
 1. Enter the following command `install.packages("path/to/file.zip", repos = NULL, type = "win.binary")`
 
### Data cleaning
Very little data cleaning is done. 
The team has decided that the data published in the commentaries (not just the annual) should reflect the data submitted to the DCS. 

Sometimes pipe characters may appear in some fields, including patient hospital number and cause line shifts. 
It is possible to identify where these have occurred by tabulating the number of characters that make up the id variable. 
One exception to this is that CDI data will need to be filtered to drop patients < 2 years old. 

All ids should be six digits long. 
Any greater or lower values are likely to indicate that a line shift has occurred. 

Ages are calculated using a mandatory surveillance algorithm to appropriately account for leap years, see `mandatory_age()` and `mandatory_age_group()` for these calculations. 

Time to onset takes into account patient location. 

Apportionment and PIR assignment are done separately from the DCS, in case there are problems with the DCS algorithm. 
The functions `assignment_algorithm()` and `apportion()` handle this. 

Each collection should be checked to ensure that every record has an attributed CCG.

### Data analysis
Four .Rmd files are found in the root directory, one for each collection. 
There is also an additional .Rmd file for further analysis of CDI data but this could be incorporated into the main CDI .Rmd
Each .Rmd creates a Word document when knitted which can be incorporated into the final report. 
Tables require further formatting however. 

Each .Rmd will produce standard outputs for the following:

#### Overall number of cases
 * graph - total rate per 100,000 population and trust-apportioned rate per 100,000
   * For MRSA this includes PIR assignment. For 2016/17, PIR assignment may replace apportionment as likely to have sufficient data by this point. 
 * table - Fyear, mid-yr popn estimate, all reported cases, rate by population, fy bed days, trust-apportioned cases, rate by beddays
 
#### Age and sex distribution
  * Graph comparing age and sex dist for 1st year vs most recent year. See function `age_sex_plot()`
  * Two tables: age and sex distribution for first year of data and one for most recent year of data.
  
#### Time to onset
 * Limited to inpatients, day patients and patients admitted to emergency assesment unit.
 * Area chart giving time to onset `aec_tto_plot()`, `tto` variable calculated with function `time_to_onset()`
 
#### Source of bacteraemia
 * Table giving trends in source of bacteraemia over time 
 * Repeat limiting to inpatient cases only - text in commentary
 
#### Geographic distribution 

 * Previously by local area team. 
 * Most recently by NHS subrgion aka "local office"
 * `aec_subregion_plot()`

### Annual tables
### Fingertips data

## Publication process
### Circulation to DH
### Circulation to publications and web publishing
