#' Plot the most likely primary focus for E. coli bacteraemia by time to onset
#'
#' Although the function takes a single argument (a data frame),
#' it relies on the presence of several variables to that data frame:
#' * \code{tto_group} The grouped time to onset, generated by \code{\link{group_tto_bacteraemia}}
#' * \code{primary_focus} One of the primary foci in \code{\link{ecoli_primary_focus}}
#' * \code{pc} The percentage that the focus occurs within tto_group
#' @param x A data frame
#' @return A ggplot2 object
#' @seealso \code{\link{group_tto_bacteraemia}} \code{\link{ecoli_primary_focus}}
#' @examples
#' \dontrun{
#' dat <- structure(list(
#' tto_group = structure(c(1L, 1L, 1L, 1L, 1L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 3L, 3L, 3L),
#' .Label = c("<2", "2-6", "ge7"), class = "factor"),
#' primary_focus = structure(c(1L, 2L, 3L, 4L, 5L, 1L, 2L, 3L, 4L, 5L, 1L, 2L, 3L, 4L, 5L),
#' .Label = c("gastro", "hepatobil", "other", "unknown", "uti"), class = "factor"),
#' pc = c(0.2, 0.2, 0.2, 0.2, 0.2, 0.5, 0.2, 0.2, 0.1, 0.3, 0.2, 0.2, 0.1, 0.1,
#' 0.1)), .Names = c("tto_group", "primary_focus", "pc"),
#' class = "data.frame", row.names = c(NA, -15L))
#'
#' p <- aec_ec_source_plot(dat)
#' p
#' }
#' @export

aec_ec_source_plot <- function(x){
  if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop("ggplot2 needed for this function to work. Please install it.",
         call. = FALSE)
  }
  if (!requireNamespace("viridis", quietly = TRUE)) {
    stop("The package *viridis* needed for this function to work. Please install it.",
         call. = FALSE)
  }
  ggplot2::ggplot(x, ggplot2::aes(x= tto_group, y = pc, group = tto_group,
                        fill = primary_focus)
  ) +
    ggplot2::geom_bar(stat = "identity") +
    #facet_wrap(~tto_group) +
    ggplot2::scale_x_discrete("Days between admission and positive specimen",
                              labels = c("<2", "2-6", "\u2265 7")) +
    ggplot2::scale_y_continuous("Per cent inpatient cases") +
    #theme(axis.ticks = element_blank(), axis.text.x = element_blank()) +
    #scale_fill_discrete("Primary focus\n of infection")
    viridis::scale_fill_viridis("Primary focus\n of infection", discrete = TRUE,
                       option = "viridis", begin = 0, end = 0.85,
                       guide = ggplot2::guide_legend(reverse = TRUE))
}
